name: sonarscan and nexus store
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup jdk
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
      
    - name: build artifact
      run: mvn clean package

    - name: deploy in tomcat
      run: |
          curl -u "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
          --upload-file target/*.war \
          "${{ secrets.TOMCAT_URL }}/manager/text/deploy?path=/java-webapp&update=true"


    - name: SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=java-webapp \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.token=$SONAR_TOKEN

    - name: Configure Maven Settings
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>nexus</id>
              <username>${{ secrets.NEXUS_USERNAME }}</username>
              <password>${{ secrets.NEXUS_PASSWORD }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Deploy WAR to Nexus
      run: |
         mvn deploy \
         - DskipTests \
         - DaltDeploymentRepository=nexus::default::${{ secrets.NEXUS_URL }}/repository/maven-snapshots/
